### ISSUE TITLE
rename to freecad.plot

### ISSUE THREAD

**Issue by looooo** [FreeCAD/freecad.plot#1]
I think we can use this naming-convention for all new-style-modules. This way we do not have different names for repo, pypi-name, python-package-name.
eg.: 
```
pip install freecad.plot
import freecad.plot
```
@yorikvanhavre  can you rename this repo to my suggestion? I guess you are able to do so as you are the admin of the FreeCAD-organization on github. To do so simple go to setting/rename-repo and call it `freecad.plot`.

**Comment by yorikvanhavre** [comment]
Done

**Comment by looooo** [comment]
thanks
