### ISSUE TITLE
Plot failing to load 

### ISSUE THREAD

**Issue by notthesmartestguy** [FreeCAD/freecad.plot#12]
running Freecad 0.19, installed from the SNAP --beta channel on Ubuntu 20.04 and I get the following error after installing PLOT
```

17:13:49  During initialization the error "No module named '_tkinter', please install the python3-tk package" occurred in freecad.plot
17:13:49  --------------------------------------------------------------------------------
17:13:49  Traceback (most recent call last):
  File "/snap/freecad/20/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'
```
Tried to install tkinter, and the system responded that it was already installed. 

I'm not a coder, but looks like an underscore in front of tkinter is causing it problems

**Comment by looooo** [comment]
I am not sure why this module is used. Can you post the output of:

```
import matplotlib.pyplot as plt
plt.plot([])
```

Normally this should show a plot embbeded in the freecad-gui, but in your case it should raise an exception. Maybe this helps to find the issue.

**Comment by notthesmartestguy** [comment]
Sorry on the delay. I tried that and no dice. Looks like the snap has it's own dependencies within the folder, so it's not calling the same python as the main system. Installing through apt seems to solve the issue. I did have to install the daily version in order for the addons to populate, but it seems to work now.

**Comment by sanguinariojoe** [comment]
This issue can be closed, right?
