### ISSUE TITLE
Provide an elaborate README file

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.plot#15]
This is instructional and displayed in the FreeCAD addon manager + visitors of this repository

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
double bump :smirk:

**Comment by chennes** [comment]
Don't worry about what AddonManager shows right now: I'm in the process of migrating it to support the new package.xml metadata file, at which point I'll submit a PR to this repo (and many others!) with a draft of the new file.

**Comment by luzpaz** [comment]
We should do this before v0.20 release. The addon manager page is unhelpful  
![Screenshot_20220526_112702](https://user-images.githubusercontent.com/4140247/170520723-e3a5da11-a2ce-4460-9f4b-43069038d90f.png)

**Comment by sanguinariojoe** [comment]
Done!
