### ISSUE TITLE
Documentation of Plot WB in the FreeCAD Wiki

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.plot#9]
Currently the documentation for Plot workbench in the FreeCAD wiki is incomplete.

The wiki page doesn't mention that Plot WB was moved out of FreeCAD in to it's own addon called `freecad.plot`  

### References
* https://freecadweb.org/wiki/Plot_Module
* https://freecadweb.org/wiki/Plot_Axes
* https://freecadweb.org/wiki/Plot_Series
* https://freecadweb.org/wiki/Plot_Grid
* https://freecadweb.org/wiki/Plot_Legend
* https://freecadweb.org/wiki/Plot_Labels
* https://freecadweb.org/wiki/Plot_Positions 
* ~https://freecadweb.org/tracker/view.php?id=2017~
* https://freecadweb.org/tracker/view.php?id=3625
* URL to appropriate freecad forum thread

Also mention that Plot also serves as a dependency for other addons like CFDoF etc...

**Comment by sanguinariojoe** [comment]
I would say the FreeCAD wiki docs shall be moved here (to the github wiki), provided Plot is not "an official module" anymore.

The fact that some official modules depends on this one is a bit weird indeed

**Comment by luzpaz** [comment]
I hear your point but still think we should keep documentation in one place if we can help it. We also have a team of wiki translators who are willing to translate.

**Comment by luzpaz** [comment]
@sanguinariojoe do you have/want wiki access?

**Comment by sanguinariojoe** [comment]
> @sanguinariojoe do you have/want wiki access?

I am sure I had wiki access in the past... But apparently I have it not anymore. So it would be great if you can grant me access

**Comment by luzpaz** [comment]
I've reset your wiki account password. Let me know if you get an email.

**Comment by sanguinariojoe** [comment]
I forgot to answer. Everything alright!

**Comment by sanguinariojoe** [comment]
- [X] https://freecadweb.org/wiki/Plot_Module
- [X] https://freecadweb.org/wiki/Plot_Save
- [X] https://freecadweb.org/wiki/Plot_Axes
- [x] https://freecadweb.org/wiki/Plot_Series
- [x] https://freecadweb.org/wiki/Plot_Grid
- [x] https://freecadweb.org/wiki/Plot_Legend
- [x] https://freecadweb.org/wiki/Plot_Labels
- [x] https://freecadweb.org/wiki/Plot_Positions

I don't consider translations

**Comment by luzpaz** [comment]
Please label sections as `==Usage==` and not `==How to use==`

**Comment by sanguinariojoe** [comment]
> Please label sections as `==Usage==` and not `==How to use==`

Sure thing! I just was duplicating the Plot_Save already existing page

**Comment by sanguinariojoe** [comment]
I also fixed a bit the tutorials:

https://wiki.freecadweb.org/Plot_Basic_tutorial
https://wiki.freecadweb.org/Plot_MultiAxes_tutorial

So for the time being I close this issue. Feel free to open new issues for doc improvements

**Comment by luzpaz** [comment]
Thanks you!!!
